image:
  # This image is built upon the following Dockerfile: .gitpod.Dockerfile
  docker pull ghcr.io/lpiot/gitpod-workspace:sha256-2e340d420aefa59a6a3690c1573b9ff4c10cdacc7c74be7d00f28988e42d0323.sig
  # You can dynamically build the image when you create a new GitPod workspace with the following lines
  # gitpod/workspace-full
  # file: .gitpod.Dockerfile
# additionalRepositories:
#     - url: https://github.com/musk8teers/container.training.git
#       # checkoutLocation is optional and relative to /workspaces.
#       # by default the location defaults to the repository name.
#       checkoutLocation: 'musk8teers/container.training'
#     - url: https://github.com/musk8teers/spring-music.git
#       # checkoutLocation is optional and relative to /workspaces.
#       # by default the location defaults to the repository name.
#       checkoutLocation: 'musk8teers/spring-music'
tasks:
  - name: workspace configuration
    command: |
      mkdir -p /home/gitpod/.ssh
      ln -s /workspace/gitpod-workspace/config/ssh-config /home/gitpod/.ssh/config
      ln -s /workspace/gitpod-workspace/config/starship.toml /home/gitpod/.config/
      echo 'eval "$(starship init bash)"' >> /home/gitpod/.bashrc
      mkdir -p /workspace/.secrets
      cp -pr /workspace/gitpod-workspace/.secrets/* /workspace/.secrets
      echo ${SOPS_AGE_KEY_FILE} | base64 --decode > /workspace/.secrets/age-keys
      awk '$0 ~ /public key/ {print $4}' /workspace/.secrets/age-keys > /workspace/.secrets/age-public-key
      sops -d --age $(cat /workspace/.secrets/age-keys) /workspace/.secrets/secrets-enc.yml > /workspace/.secrets/secrets.yml
  - name: pre-requisite for container.training
    before: |
      echo "pre-requisite for container.training"
      echo "make /dev/stderr writable"
      sudo chmod go+rw /dev/pts/?
      echo "Activate SSH agent"
      eval $(ssh-agent) ; ssh-add && echo "SSH_AUTH_SOCK=${SSH_AUTH_SOCK}"
      echo "Configure Digital Ocean CLI"
      doctl auth init --access-token $(tail -1 /workspace/.secrets/gitpod-digitalocean.token)
      echo "configure autocomplete"
      echo '# Scaleway CLI autocomplete initialization.' >> /home/gitpod/.bashrc
      echo 'eval "$(/usr/local/bin/scw autocomplete script shell=bash)"' >> /home/gitpod/.bashrc
vscode:
  extensions:
    - yzhang.markdown-all-in-one
    - Gruntfuggly.todo-tree
    - hashicorp.terraform
    - hashicorp.hcl
    - tamasfe.even-better-toml
    - lextudio.restructuredtext

workspaceLocation:
  "."
