image:
  # This image is built upon the following Dockerfile: .gitpod.Dockerfile
  ghcr.io/lpiot/gitpod-workspace:main
  # You can dynamically build the image when you create a new GitPod workspace with the following lines
  # gitpod/workspace-full
  # file: .gitpod.Dockerfile
tasks:
  - name: filesystem reconfiguration
    init: |
      mkdir -p /home/gitpod/.ssh
      cp -pr /workspace/gitpod-workspace/ssh-config /home/gitpod/.ssh/config
    command: |
      echo "Nothing here."
  - name: pre-requisite for container.training
    init: |
      echo "pre-requisite for container.training"
      echo "clone the git repositories"
      git clone https://github.com/musk8teers/container.training.git
      git clone https://github.com/musk8teers/spring-music.git
      echo "make /dev/stderr writable"
      sudo chmod go+rw /dev/pts/1
      echo "Activate SSH agent"
      eval $(ssh-agent) ; ssh-add && echo "SSH_AUTH_SOCK=${SSH_AUTH_SOCK}"
    command: |
      echo "TODO: start app"
vscode:
  extensions:
    - yzhang.markdown-all-in-one
    - Gruntfuggly.todo-tree
workspaceLocation:
  "."
